export const POPULATION_PREFECTURE_REQUEST = 'POPULATION_PREFECTURE_REQUEST';
export const POPULATION_PREFECTURE_SUCCESS = 'POPULATION_PREFECTURE_SUCCESS';
export const POPULATION_PREFECTURE_FAILURE = 'POPULATION_PREFECTURE_FAILURE';

export const POPULATION_PREFECTURE_NO_CHECKED_REQUEST =
  'POPULATION_PREFECTURE_NO_CHECKED_REQUEST';
export const POPULATION_PREFECTURE_NO_CHECKED_SUCCESS =
  'POPULATION_PREFECTURE_NO_CHECKED_SUCCESS';
export const POPULATION_PREFECTURE_NO_CHECKED_FAILURE =
  'POPULATION_PREFECTURE_NO_CHECKED_FAILURE';

export const POPULATION_PREFECTURE_CHECKED_REQUEST =
  'POPULATION_PREFECTURE_CHECKED_REQUEST';
export const POPULATION_PREFECTURE_CHECKED_SUCCESS =
  'POPULATION_PREFECTURE_CHECKED_SUCCESS';
export const POPULATION_PREFECTURE_CHECKED_FAILURE =
  'POPULATION_PREFECTURE_CHECKED_FAILURE';
